config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: "airquality#index", as: 'root'
  resources :airquality, only: [:create]
  resources :alert, only: [:show, :create, :destroy, :index, :edit]

  resources :youralerts, only: [:index]
end

app/models/air_index.rb
class AirIndex < ApplicationRecord
  validates :index, presence: true, uniqueness: true

  has_many :weather_points
  has_many :alerts
end

app/models/alert.rb
class Alert < ApplicationRecord
  validates :phone, :air_index_id, :zipcode, presence: true
  validates_inclusion_of :active, :in => [true, false]
  belongs_to :air_index

  def styled_number
    phone_number = self.phone
    (phone_number[0..2] + "-" + phone_number[3..5] + "-" +  phone_number[6..9])
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_point.rb
class WeatherPoint < ApplicationRecord
  validates :city, :state, :country, :zipcode, :us_aqi, :air_index_id,
            :latitude, :longitude, presence: true

  belongs_to :air_index

  def self.get_us_rating(aqi)
    if 0 <= aqi && aqi <= 50
      return 1
    elsif 51 <= aqi && aqi <= 100
      return 2
    elsif 101 <= aqi && aqi <= 150
      return 3
    elsif 151 <= aqi && aqi <= 200
      return 4
    elsif 201 <= aqi && aqi <= 300
      return 5
    elsif 301 <= aqi && aqi <= 500
      return 6
    else
      return 7
    end
  end

end

app/controllers/airquality_controller.rb
class AirqualityController < ApplicationController
  def index
    @weatherpoint = WeatherPoint.last
  end

  def create
    local_air_data = AirDataService.new.get_air_quality(params["zipcode"])
    wp = WeatherPoint.new(local_air_data)

    wp.save
    result_hash = wp.as_json
    result_hash[:rating] = wp.air_index.index
    respond_to do |format|
      format.json { render json: result_hash.to_json, :status => :ok}
    end
  end

end

app/controllers/alert_controller.rb
class AlertController < ApplicationController
  def index
  end

  def create
    alert = Alert.new(alert_params)
    alert.save
    TwilioService.send_intro_message(alert.phone, alert.zipcode, alert.air_index.index)
    respond_to do |format|
      format.json { render json: alert.to_json, :status => :ok}
    end
  end

  def show
    @alert = Alert.find(params[:id])
  end

  def destroy
    alert = Alert.find(alert_params["id"])
    alert.active = false
    alert.save
    user_alerts = Alert.where(phone: alert.phone, active: true)
    if user_alerts.empty?
      flash[:success] = 'Successfully canceled all alerts!'
      redirect_to root_path
    else
      redirect_to alert_index_path(phone: alert.phone)
    end
  end

  private
    def alert_params
      params[:air_index_id] = AirIndex.find_by(index: params[:alert_level]).id if params[:alert_level]
      params.permit(:phone, :air_index_id, :zipcode, :active, :id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/youralerts_controller.rb
class YouralertsController < ApplicationController
  def index
    user_alerts = Alert.where(phone: alert_params["number"], active: true).to_json(:include => {:air_index => {:only => :index}}, :only => [:zipcode, :id])
    respond_to do |format|
      format.json { render json: user_alerts, :status => :ok}
    end
  end

  private
    def alert_params
      params.permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airquality/index.html.erb
<div id="map-background"></div>

<div class="top-bar">
  <p id="logo">Air-Quality-Alert.net</p>
  <a id ="header-question" href="/">What is my air quality?</a>
  <%= link_to "Cancel Alert", alert_index_path, id: "cancel-button" %>
    <div id="helpful-flash" class="flash-message">
      <h2 id="flash-text">Please enter a valid 5 digit zipcode</h2>
    </div>
    <div id="helpful-phone-flash" class="flash-message">
      <h2 id="flash-text">Please enter a 10 valid digit phone number containing only numbers</h2>
    </div>
    <% if flash.any?%>
      <div id="generic-flash" class="flash-message">
        <h2 id="flash-text"> <%= flash["success"] %> </h2>
      </div>
    <% end %>
</div>

<div id="zipcode-form">
    <%= text_field_tag 'zipcode', nil, placeholder: 'Enter Zipcode', id: 'zipcode-input', onfocus: "this.placeholder = ''", onBlur: "this.placeholder = 'Enter Zipcode'", autocomplete:"off" %> <br>
    <%= submit_tag "Get Air Quality", id:'submit-button', type:'button' %>
</div>

<aside class="results-box">
    <span id="image-span"></span>
    <div id="result-text">
      <p>The Air Quality in  <span class="text-emphasis" id="city-country"> </span> is
        <span class="text-emphasis" id="rating"> </span></p>
    </div>
    <div id="call-box">
      <p id="sales-copy">Get FREE Updates When The Air Quality In Your Area Reaches <span id="dangerous"> Dangerous  </span> Levels</p>
      <p id="call-to-action"> Text me at <span id="phone"></span> if the air quality in <span id='city-zip'></span> is <span id="drp-btn"></span> <span id="sbmt-text-info"> </span></p>
    </div>
</aside>

<script>

  $('.results-box').hide();
  $('#helpful-flash').hide();
  $('#helpful-phone-flash').hide();
  $('#generic-flash').hide();

  show_generic_flash();
  function show_generic_flash() {
    $('#generic-flash').slideDown("slow").fadeOut(5000);
  }

  var updatedBefore = false;

  function updatePageStyle() {
    $('#cancel-button').fadeOut(200);
    $('#map-background').css("height", "40%");
    $('.results-box').slideToggle();
    $('#zipcode-form').css({"width":"100%","margin-top":"5em","margin-left":"","margin-right":"", "text-align":""});
    $('#zipcode-input').css({"width":"50%","float":"left", "margin-left": "10%", "margin-top": "5%"});
    $('#submit-button').css({"margin-top":"","margin-right":"15%","float":"right"});
  }

  function recenterMap() {
    map.setCenter({lat: 47.45, lng: -122.3321});
  }

  $('#phone').append(
    $('<input/>').attr("placeholder", "555-555-5555").attr("id", "phone-input")
  )

  $('#drp-btn').append(
    $('<select>').append(
      $("<option>").text("Good"),
      $("<option>").text("Moderate"),
      $("<option>").text("Unhealthy For Sensitive Groups"),
      $("<option>").text("Unhealthy").attr('selected', true),
      $("<option>").text("Very Unhealthy"),
      $("<option>").text("Hazardous")
    )
  )

  $('#sbmt-text-info').append(
    $('<button>').html('Submit')
  )

  function get_smiley_path(rating) {
    var imageStore = {"Good": "good.png", "Moderate": "moderate.png",
                      "Unhealthy For Sensitive Groups": "sensitive.png", "Unhealthy": 'unhealthy.png',
                      "Very Unhealthy": "very_unhealthy.png", "Hazardous": "hazardous.png"}
    return imageStore[rating];
  }

  function highlightFlash() {
    $('.results-box').addClass('backgroundColorFlash')
    setTimeout(function () {
      $('.results-box').removeClass('backgroundColorFlash');
    }, 380);
  }

  $('#sbmt-text-info').click(function(){
    var alertAQI = $('#drp-btn option:selected').text()
    var phoneNumber = $('#phone-input').val()
    var zipcode = $("#city-zip").html()
    if (phoneNumber.length != 10) {
      $('#helpful-phone-flash').slideDown("slow").fadeOut(5000);
    } else {
      $.ajax({
        type: "POST",
        url: "/alert",
        data: {"zipcode": zipcode, "phone": phoneNumber, "alert_level": alertAQI, "active": true },
        dataType: "json",
        success: function(result) {
          // var path = 'http://localhost:3000/alert/' + result["id"]
          var path = 'https://air-quality-alert.herokuapp.com/alert/' + result["id"]
          window.location = path
        },
        error: function(data){
          $('#helpful-phone-flash').slideDown("slow").fadeOut(5000);
        }
      });
    }
  })

  $('#submit-button').click(function(){
    var zipcode = $('#zipcode-input').serializeArray()[0]["value"];
    if (zipcode.length != 5) {
      $('#helpful-flash').slideDown("slow").fadeOut(5000);
    } else {
      submitFormData(zipcode);
    }
  });

  function submitFormData(zipcode) {
    $.ajax({
      type: "POST",
      url: "/airquality",
      data: {"zipcode": zipcode},
      dataType: "json",
      success: function(result) {
        if (updatedBefore) { highlightFlash(); }
        $('#city-country').text(`${result["city"]}, ${result["country"]}`);
        $('#city-zip').text(`${result["zipcode"]}`);
        $('#rating').text(result["rating"]);
        $('#image-span').empty().append( `<img id='emoji-image' src='/assets/${get_smiley_path(result["rating"])}' >`)
        if (updatedBefore) { } else {
          recenterMap();
          updatePageStyle();
          updatedBefore = true;
        }
      },
      error: function(data){
        $('#helpful-flash').slideDown("slow").fadeOut(5000);
    }
    });
  }

  $('#zipcode-form').keyup(function(){
    checkInput("#zipcode-input", 5, '#helpful-flash')
  });

  $('#phone-input').keyup(function(){
    checkInput("#phone-input", 10, '#helpful-phone-flash')
  });

</script>

app/views/alert/index.html.erb
<div id="map-background"></div>

<div class="top-bar">
  <p id="logo">Air-Quality-Alert.net</p>
  <a id ="header-question" href="/">What is my air quality?</a>
  <div id="helpful-phone-flash" class="flash-message">
    <h2 id="flash-text">Please enter a 10 digit phone number containing only numbers</h2>
  </div>
  <div class="flash-message" id="no-alerts-flash">
    <h2 id="flash-text">No alerts found for <span id="alert-number"></span></h2>
  </div>
  <div id="success-flash" class="flash-message">
    <h2 id="flash-text"> Successfully canceled alert! </h2>
  </div>
</div>


<div id="alert-box">
  <h1>Enter your phone number to find all your alerts</h1>
  <div id="phone-form">
    <%= text_field_tag 'Phone', nil, placeholder: 'Enter Phone', id: 'find-phone-input', onfocus: "this.placeholder = ''", onBlur: "this.placeholder = 'Enter Phone'", autocomplete:"off" %> <br>
    <%= submit_tag "Find My Alerts", id:'submit-button', type:'button' %>
  </div>
</div>

<div id="your-alerts">
  <h1 class="font-style">Alerts for <span id="your-phone"></span></h1>
  <div id="the-alerts">
  </div>
</div>

<script>
  $('#your-alerts').hide();
  $('#helpful-phone-flash').hide();
  $('#no-alerts-flash').hide();
  $('#success-flash').hide();

  function recenterMap() {
    map.setCenter({lat: 47.45, lng: -122.3321});
  }

  function stylePhoneNumber(phoneNumber) {
    return phoneNumber.substring(0,3) + "-" + phoneNumber.substring(3,6) + "-" + phoneNumber.substring(6,10);
  }

  $('#find-phone-input').keyup(function(){
    checkInput("#find-phone-input", 10, '#helpful-phone-flash')
  });

  $('#submit-button').click(function(){
    var number = $('#find-phone-input').serializeArray()[0]["value"];
      submitFormData(number, "NOT-re-render");
  });

  function submitFormData(number, sentFrom) {
    $.ajax({
      type: "GET",
      url: "/youralerts",
      data: {"number": number},
      dataType: "json",
      success: function(result) {
        if (result.length == 0) {
          $('#alert-number').text(stylePhoneNumber(number));
          $('#no-alerts-flash').slideDown("slow").fadeOut(5000);
        } else {
          showResults(result, number, sentFrom);
        }
      }
    });
  }

  autoSearchNumber();
  function autoSearchNumber() {
    var phone = window.location.search.split('?')[1] ? window.location.search.split('=')[1] : 0;
    if (phone != 0) {
      submitFormData(phone, "re-render")
      $('#success-flash').slideDown("slow").fadeOut(5000);
    }
  }

  function changeStyles(phoneNumber) {
    $('#alert-box').hide();
    recenterMap();
    $('#map-background').css("height", "20%");
    $('#your-phone').text(stylePhoneNumber(phoneNumber));
  }

  function showResults(result, phoneNumber, sentFrom){
    if (sentFrom == "re-render") {
      $('#your-alerts').show()
      changeStyles(phoneNumber);
    } else {
      changeStyles(phoneNumber);
      $('#your-alerts').slideToggle()
    }
    appendAlerts(result)
  }

  function appendAlerts(result) {
    for (var i = 0; i < result.length; i++) {
      var myAuthToken = "<%= form_authenticity_token %>"
      var delete_button = `<form class="button_to" method="post" action="/alert/${result[i].id}"><input type="hidden" name="_method" value="delete"><input id="cancel-service" class="margin-bottom-10" type="submit" value="Cancel Alert"> <input type="hidden" name="authenticity_token" value="${myAuthToken}"> </form>`
      $("#the-alerts").append(`<h2 class="font-style">Alert ${i+1}: Alert when air quality is <span class="mild-emphasis">${result[i].air_index.index}</span> in <span class="mild-emphasis">${result[i].zipcode}</span> <span id="delete-form"> ${delete_button} </span> <h2>`);
    }
  }

</script>

app/views/alert/show.html.erb
<div id="map-background"></div>

<div class="top-bar">
  <p id="logo">Air-Quality-Alert.net</p>
  <a id ="header-question" href="/">What is my air quality?</a>
</div>

<div id="alert-box">
  <% if @alert.active %>
    <h1>Alert Successfully Set!</h1>
    <h3>We'll send a text to <%= @alert.styled_number %></h3>
    <h3>When the air quality in <%= @alert.zipcode %> </h3>
    <h3>Is at or below the US governments '<%= @alert.air_index.index %>' designation </h3>
    <h5>Sending a welcome text now to confirm we have the right number one file</h5>
    <h1>Thanks for using air quality alert!</h1>
    <%= button_to "Cancel Alert", alert_path(:id => @alert.id), :method => :delete, id: "cancel-service"  %>
  <% else %>
  <br>
    <h1>This Alert has been canceled!</h1>
    <%= button_to  "Set Another Alert", root_path, :method => :get, id:'submit-button', type:'button' %>
    <br>
    <% end %>
</div>

<script>

  $('#cancel-service').click(function(){
    $.ajax({
      type: "POST",
      url: "/alert",
      data: {},
      dataType: "json",
      success: function(result) {
      }
    });
  })

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirQualityAlert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>


  <script>
  var map;
    function initMap() {

      var styledMapType = new google.maps.StyledMapType(
        [
  {
  "featureType": "administrative.land_parcel",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "administrative.neighborhood",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "poi",
  "elementType": "labels.text",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "poi.business",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "poi.park",
  "elementType": "labels.text",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "road",
  "elementType": "labels",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "road.arterial",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "road.highway",
  "elementType": "labels",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "road.local",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  },
  {
  "featureType": "water",
  "elementType": "labels.text",
  "stylers": [
  {
    "visibility": "off"
  }
  ]
  }
  ],
          {name: 'Styled Map'});

      map = new google.maps.Map(document.getElementById('map-background'), {
        center: {lat: 47.6062, lng: -122.3321},
        streetViewControl: false,
        scaleControl: false,
        draggable: false,
        zoomControl: false,
        zoom: 10,
        mapTypeControlOptions: {
          mapTypeIds: []
        }
      });
      map.mapTypes.set('styled_map', styledMapType);
      map.setMapTypeId('styled_map');
    }


  function checkInput(buttonClicked, properInputLength, flashMessage) {
    var regex = /[0-9]|\./;
    var inputVal = $(buttonClicked).val()
    var inputLength = inputVal.length;
    var keyPressed = event.keyCode

    if (!regex.test(event.key) && keyPressed != 8 && keyPressed != 13 && keyPressed != 46 && keyPressed != 13) {
      $(buttonClicked).val(inputVal.slice(0, -1));
      $(flashMessage).slideDown("slow").fadeOut(5000);
      return false
    } else if (inputLength > properInputLength) {
      $(flashMessage).slideDown("slow").fadeOut(5000);
      $(buttonClicked).val(inputVal.slice(0, -1));
      return false
    }
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjydTLy1DwBK6nEEeVhmzhGnyAcTUnMoY&callback=initMap">
</script>
</html>